[tool.poetry]
name = "gapstatistics"
version = "0.1.0"
description = "A library for calculating the gap statistics for clustering algorithms"
authors = ["Tim Loehr <timloehr@icloud.com>"]
license = "MIT"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gapstatistics"
authors = [
    {name = "Tim Loehr", email = "timloehr@icloud.com"}
]
description = "A library for calculating the gap statistics for clustering algorithms"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "scikit-learn",
    "matplotlib",
    "scipy"
]